### ISSUE TITLE
Lightmap island selector highlights wrong objects

### ISSUE THREAD

**Issue by teehzero** [pema99/GITweaks#4]
Unity 2022.3.22f1, Bakery + https://github.com/z3y/XatlasLightmap

Let me know if I can provide anything else

**Comment by pema99** [comment]
The most helpful thing you can give me is the scene you tested with including lightmaps (for example as a unitypackage)

**Comment by teehzero** [comment]
I'll try to cook up something more minimal

**Comment by teehzero** [comment]
[gitweaks.xatlas.unitypackage.zip](https://github.com/user-attachments/files/17724157/gitweaks.xatlas.unitypackage.zip)

**Comment by pema99** [comment]
Ah, I see what's gone wrong. This scene has each chart packed individually, meaning that all objects have the same UV bounds in the lightmap - the _entire_ lightmap. That isn't something you can do out of the box with Unity's lightmapper or with Bakery. The code that attempts to find the object that the mouse is hovering over is based on UV bounding boxes. In case there are overlapping bounding boxes, I just pick the smallest one. Since all the bounding boxes are identical here, the feature completely breaks down.

**Comment by pema99** [comment]
It might not seem like it, but solving that involves solving a much more tricky problem than what I am currently doing. I might give a try, not sure yet

**Comment by pema99** [comment]
I pushed a change to make the selection more precise, feel free to try it out  https://github.com/pema99/GITweaks/commit/a82ee5cfc403a6267f3b5d12a98ad363a55adb49

It's more expensive, as it relies on rasterizing every instance with an overlapping UV bound, but should handle scenes like the ones you've sent

**Comment by teehzero** [comment]
https://github.com/user-attachments/assets/d3a1c750-49e2-43f4-a4da-90e2fe3651ba
not perfect but this is a huge improvement 🕺

**Comment by pema99** [comment]
I just pushed another small fix, might improve that failure case you were seeing - try it out

**Comment by pema99** [comment]
https://github.com/pema99/GITweaks/commit/7530a07953ebf8d8a80ce9b75c9075a096419b9f

**Comment by teehzero** [comment]
100% perfect
